spring.application.name=auth

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth_db
spring.datasource.username=${DB_USERNAME_AUTH:auth_user}
spring.datasource.password=${DB_PASSWORD_AUTH:auth_password}

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

# JWT configuration
jwt.secret=${JWT_SECRET:mysecretkey}
jwt.expiration=${JWT_EXPIRATION:3600000}