spring.application.name=auth

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME_AUTH:auth_db}
spring.datasource.username=${DB_USER_AUTH:auth_user}
spring.datasource.password=${DB_PASSWORD_AUTH:auth_password}

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT configuration
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}