spring.application.name=auth

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
spring.datasource.username=${DB_USER:auth_user}
spring.datasource.password=${DB_PASSWORD:auth_password}

spring.jpa.hibernate.ddl-auto=update

# JWT configuration
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}