#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
CREATE USER ${DB_USER_AUTH} WITH PASSWORD '${DB_PASSWORD_AUTH}';
CREATE USER ${DB_USER_WORKSPACE} WITH PASSWORD '${DB_PASSWORD_WORKSPACE}';
CREATE USER ${DB_USER_INGESTION} WITH PASSWORD '${DB_PASSWORD_INGESTION}';

CREATE DATABASE ${DB_NAME_AUTH} OWNER ${DB_USER_AUTH};
CREATE DATABASE ${DB_NAME_WORKSPACE} OWNER ${DB_USER_WORKSPACE};
CREATE DATABASE ${DB_NAME_INGESTION} OWNER ${DB_USER_INGESTION};
EOSQL