spring.application.name=ingestion

server.port=8082

server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME_INGESTION:ingestion_db}
spring.datasource.username=${DB_USER_INGESTION:ingestion_user}
spring.datasource.password=${DB_PASSWORD_INGESTION}

spring.jpa.hibernate.ddl-auto=create

authlib.jwt.issuer=${JWT_ISSUER:devault-auth}

authlib.jwks.uri=http://${JWKS_HOST:localhost}:8081/.well-known/jwks.json

ingestion.security.key=${INGESTION_TOKEN_ENCRYPTION_KEY}