spring.application.name=workspace

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME_WORKSPACE:workspace_db}
spring.datasource.username=${DB_USER_WORKSPACE:workspace_user}
spring.datasource.password=${DB_PASSWORD_WORKSPACE:workspace_password}

spring.jpa.hibernate.ddl-auto=update
